#ifndef EEPROM_LOCATION_H
#define EEPROM_LOCATION_H

#define EEPROM_SIZE 512
#define SSID_SIZE_LOCATION 0
#define PASSWORD_SIZE_LOCATION 1
#define SAVED_START_HOUR_LOCATION 2
#define SAVED_START_MINUTES_LOCATION 3
#define SAVED_STOP_HOUR_LOCATION 4
#define SAVED_STOP_MINUTES_LOCATION 5
#define SAVED_SSID_LOCATION 10
#define SAVED_PASSWORD_LOCATION 50

#endif